import { AgentConfigField } from "@/types";

export const agentConfiguration: AgentConfigField[] = [
    {
        label: "language",
        type: "dropdown",
        options: ["English", "French", "Spanish", "German", "Portuguese", "Italian", "Dutch", "Turkish", "Arabic"],
        description: "Primary language of the post.",
        default: "English",
        required: true,
    },
    {
        label: "industry",
        type: "dropdown",
        options: [
            "React.js",
            "Vue.js",
            "Angular",
            "TypeScript",
            "JavaScript (ES6+)",
            "HTML5 & CSS3",
            "Sass/Less/Stylus",
            "Tailwind CSS",
            "Next.js",
            "Nuxt.js",
            "WebAssembly",
            "PWA (Progressive Web Apps)",

            // Backend Technologies (Node.js & Others)
            "Node.js",
            "NestJS",
            "Express.js",
            "Python/Django",
            "Python/Flask",
            "Java/Spring Boot",
            "Go (Golang)",
            "C#/.NET",
            "PHP/Laravel",
            "Ruby on Rails",
            "Rust",

            // Databases & Data Storage
            "PostgreSQL",
            "MongoDB",
            "MySQL",
            "Redis",
            "Elasticsearch",
            "Kafka",
            "NoSQL",
            "SQL",

            // DevOps & Cloud Computing
            "AWS",
            "Azure",
            "Google Cloud Platform (GCP)",
            "Kubernetes (K8s)",
            "Docker",
            "Terraform",
            "CI/CD",
            "GitHub Actions",
            "GitLab CI",
            "Shell Scripting",
            "Ansible",
            "Prometheus & Grafana",

            // Artificial Intelligence & Data Science
            "Machine Learning (ML)",
            "Deep Learning",
            "TensorFlow",
            "PyTorch",
            "Scikit-learn",
            "Pandas & NumPy",
            "Natural Language Processing (NLP)",
            "Computer Vision",
            "Data Analysis",
            "Big Data",

            // Core Engineering & Methodologies
            "System Design",
            "Microservices",
            "Design Patterns",
            "Data Structures",
            "Algorithms",
            "Object-Oriented Programming (OOP)",
            "Functional Programming",
            "Testing (Unit, Integration, E2E)",
            "Code Review",
            "Agile/Scrum",
            "Kanban",
            "MVP (Minimum Viable Product)",
            "Design System",

            // Specialized/Emerging Technologies
            "Solidity",
            "Smart Contracts",
            "Web3.js",
            "DApps (Decentralized Applications)",
            "AR/VR Development (Unity/Unreal)",
            "Cybersecurity Principles",
        ],
        description: "Select the closest industry trend",
        default: "Software Development",
        required: true,
    },
    {
        label: "format",
        type: "dropdown",
        options: [
            "Short post (50-150 words)",
            "Medium post (150-300 words)",
            "Long-form text (300+ words)",
            "List post (3-5 bullet points)",
            "Question-based post",
            "Personal story",
        ],
        description: "Preferred length and structure for a LinkedIn post.",
        default: "Short post (50-150 words)",
        required: true,
    },
    {
        label: "cta",
        type: "dropdown",
        options: [
            "default",
            "Ask a question",
            "Invite comments",
            "Drive to DM",
            "Link in comments",
            "Subscribe/Follow",
            "Join waitlist",
        ],
        description: "Call-to-action at the end.",
        default: "Invite comments",
        required: true,
    },
    {
        label: "includeEmojis",
        type: "dropdown",
        options: ["None", "Subtle", "Moderate"],
        description: "Emoji usage appropriate for LinkedIn.",
        default: "Subtle",
        required: true,
    },
    {
        label: "hashtagMode",
        type: "dropdown",
        options: ["Auto", "Manual", "Preset: Tech", "Preset: Career", "Preset: Marketing", "Preset: Leadership"],
        description: "How to generate hashtags.",
        default: "Auto",
        required: true,
    },
    {
        label: "manualHashtags",
        type: "text",
        description: "Used only if hashtagMode is Manual. Comma-separated hashtags without #.",
        default: "",
        required: false,
    },
    {
        label: "maxHashtags",
        type: "number",
        description: "Cap number of hashtags (LinkedIn recommends ~3–10).",
        default: 8,
        required: true,
    },
    {
        label: "tagEntities",
        type: "text",
        description: "Comma-separated people/companies to tag (names; you'll map to @handles).",
        default: "",
        required: false,
    }
]
