export const agentConfiguration = [
    {
        label: "language",
        type: "dropdown",
        options: ["English", "French", "Spanish", "German", "Portuguese", "Italian", "Dutch", "Turkish", "Arabic"],
        description: "Primary language of the post.",
        default: "English",
        required: true,
    },
    {
        label: "industry",
        type: "dropdown",
        options: [
            "Technology",
            "Artificial Intelligence",
            "Machine Learning",
            "Data Science",
            "Cybersecurity",
            "Cloud Computing",
            "Blockchain",
            "Cryptocurrency",
            "Web3",
            "Software Development",
            "Startups",
            "Venture Capital",
            "Product Management",
            "E-commerce",
            "Gaming",
            "AR/VR (Augmented & Virtual Reality)",
            "Finance",
            "Banking",
            "Fintech",
            "Investment",
            "Real Estate",
            "Insurance",
            "Consulting",
            "Entrepreneurship",
            "Marketing",
            "Sales",
            "Business Strategy",
            "Economy",
            "Trade",
            "Supply Chain & Logistics",
            "Remote Work",
            "Hybrid Work",
            "Career Growth",
            "Leadership",
            "Workplace Culture",
            "Human Resources",
            "Diversity & Inclusion",
            "Future of Work",
            "Personal Branding",
            "Social Media",
            "Content Creation",
            "Influencer Marketing",
            "Streaming Platforms",
            "Movies & Nollywood",
            "Hollywood",
            "Music",
            "Podcasts",
            "Sports",
            "Esports",
            "Fashion",
            "Lifestyle",
            "Food & Beverage",
            "Travel & Tourism",
            "Education",
            "Online Learning",
            "Research",
            "Space Exploration",
            "Biotechnology",
            "Healthcare",
            "Pharmaceuticals",
            "Climate Science",
            "Sustainable Development",
            "Politics",
            "Elections",
            "Governance",
            "Policy",
            "Social Justice",
            "Climate Change",
            "Environment",
            "Nonprofits & NGOs",
            "Global Affairs",
            "African Tech",
            "Asian Markets",
            "European Union",
            "US Tech",
            "Middle East Business",
            "Latin America Trends",
            "Nollywood",
            "Afrobeats",
        ],
        description: "Select the closest industry trend",
        default: "Software Development",
        required: true,
    },
    {
        label: "tone",
        type: "multiselect",
        options: [
            "Authoritative",
            "Conversational",
            "Inspirational",
            "Analytical",
            "Storytelling",
            "Practical",
            "Bold",
            "Empathetic",
            "Witty",
            "Formal",
            "Casual",
        ],
        description: "Tone(s) of voice to carry throughout the post.",
        default: ["Authoritative", "Practical"],
        required: true,
    },
    {
        label: "format",
        type: "dropdown",
        options: [
            "Short post (50-150 words)",
            "Medium post (150-300 words)",
            "Long-form text (300+ words)",
            "List post (3-5 bullet points)",
            "Question-based post",
            "Personal story",
        ],
        description: "Preferred length and structure for a LinkedIn post.",
        default: "Short post (50-150 words)",
        required: true,
    },
    {
        label: "cta",
        type: "dropdown",
        options: [
            "default",
            "Ask a question",
            "Invite comments",
            "Drive to DM",
            "Link in comments",
            "Subscribe/Follow",
            "Join waitlist",
        ],
        description: "Call-to-action at the end.",
        default: "Invite comments",
        required: true,
    },
    {
        label: "includeEmojis",
        type: "dropdown",
        options: ["None", "Subtle", "Moderate"],
        description: "Emoji usage appropriate for LinkedIn.",
        default: "Subtle",
        required: true,
    },
    {
        label: "hashtagMode",
        type: "dropdown",
        options: ["Auto", "Manual", "Preset: Tech", "Preset: Career", "Preset: Marketing", "Preset: Leadership"],
        description: "How to generate hashtags.",
        default: "Auto",
        required: true,
    },
    {
        label: "manualHashtags",
        type: "text",
        description: "Used only if hashtagMode is Manual. Comma-separated hashtags without #.",
        default: "",
        required: false,
    },
    {
        label: "maxHashtags",
        type: "number",
        description: "Cap number of hashtags (LinkedIn recommends ~3–10).",
        default: 8,
        required: true,
    },
    {
        label: "tagEntities",
        type: "text",
        description: "Comma-separated people/companies to tag (names; you'll map to @handles).",
        default: "",
        required: false,
    }
] as const

export type AgentConfigField = (typeof agentConfiguration)[number]
