export const industries = [
    "Technology",
    "Artificial Intelligence",
    "Machine Learning",
    "Data Science",
    "Cybersecurity",
    "Cloud Computing",
    "Blockchain",
    "Cryptocurrency",
    "Web3",
    "Software Development",
    "Startups",
    "Venture Capital",
    "Product Management",
    "E-commerce",
    "Gaming",
    "AR/VR (Augmented & Virtual Reality)",
    "Finance",
    "Banking",
    "Fintech",
    "Investment",
    "Real Estate",
    "Insurance",
    "Consulting",
    "Entrepreneurship",
    "Marketing",
    "Sales",
    "Business Strategy",
    "Economy",
    "Trade",
    "Supply Chain & Logistics",
    "Remote Work",
    "Hybrid Work",
    "Career Growth",
    "Leadership",
    "Workplace Culture",
    "Human Resources",
    "Diversity & Inclusion",
    "Future of Work",
    "Personal Branding",
    "Social Media",
    "Content Creation",
    "Influencer Marketing",
    "Streaming Platforms",
    "Movies & Nollywood",
    "Hollywood",
    "Music",
    "Podcasts",
    "Sports",
    "Esports",
    "Fashion",
    "Lifestyle",
    "Food & Beverage",
    "Travel & Tourism",
    "Education",
    "Online Learning",
    "Research",
    "Space Exploration",
    "Biotechnology",
    "Healthcare",
    "Pharmaceuticals",
    "Climate Science",
    "Sustainable Development",
    "Politics",
    "Elections",
    "Governance",
    "Policy",
    "Social Justice",
    "Climate Change",
    "Environment",
    "Nonprofits & NGOs",
    "Global Affairs",
    "African Tech",
    "Asian Markets",
    "European Union",
    "US Tech",
    "Middle East Business",
    "Latin America Trends",
    "Nollywood",
    "Afrobeats",
]

