export const industries = [
    // Frontend Technologies (JS Ecosystem)
    "React.js",
    "Vue.js",
    "Angular",
    "TypeScript",
    "JavaScript (ES6+)",
    "HTML5 & CSS3",
    "Sass/Less/Stylus",
    "Tailwind CSS",
    "Next.js",
    "Nuxt.js",
    "WebAssembly",
    "PWA (Progressive Web Apps)",

    // Backend Technologies (Node.js & Others)
    "Node.js",
    "NestJS",
    "Express.js",
    "Python/Django",
    "Python/Flask",
    "Java/Spring Boot",
    "Go (Golang)",
    "C#/.NET",
    "PHP/Laravel",
    "Ruby on Rails",
    "Rust",

    // Databases & Data Storage
    "PostgreSQL",
    "MongoDB",
    "MySQL",
    "Redis",
    "Elasticsearch",
    "Kafka",
    "NoSQL",
    "SQL",

    // DevOps & Cloud Computing
    "AWS",
    "Azure",
    "Google Cloud Platform (GCP)",
    "Kubernetes (K8s)",
    "Docker",
    "Terraform",
    "CI/CD",
    "GitHub Actions",
    "GitLab CI",
    "Shell Scripting",
    "Ansible",
    "Prometheus & Grafana",

    // Artificial Intelligence & Data Science
    "Machine Learning (ML)",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Pandas & NumPy",
    "Natural Language Processing (NLP)",
    "Computer Vision",
    "Data Analysis",
    "Big Data",

    // Core Engineering & Methodologies
    "System Design",
    "Microservices",
    "Design Patterns",
    "Data Structures",
    "Algorithms",
    "Object-Oriented Programming (OOP)",
    "Functional Programming",
    "Testing (Unit, Integration, E2E)",
    "Code Review",
    "Agile/Scrum",
    "Kanban",
    "MVP (Minimum Viable Product)",
    "Design System",

    // Specialized/Emerging Technologies
    "Solidity",
    "Smart Contracts",
    "Web3.js",
    "DApps (Decentralized Applications)",
    "AR/VR Development (Unity/Unreal)",
    "Cybersecurity Principles",
];